"""Cognitive layer contracts, session services, and persistence boundaries."""

from cognition.contracts import (
    AssistantResponse,
    AssistantResponseType,
    CognitiveInteractionResult,
    ConversationContextContentClassification,
    ConversationContextSnapshot,
    ConversationContextTurn,
    ConversationRole,
    ConversationSessionSnapshot,
    ConversationSessionStatus,
    ConversationTurn,
    ConversationTurnInput,
    InvalidConversationTurnError,
    IntentCategory,
    IntentConfidence,
    IntentEvidence,
    IntentInterpretationInput,
    InterpretedIntent,
    ResponseCompositionInput,
    ResponseCompositionResult,
)
from cognition.context import (
    DEFAULT_CONTEXT_MAX_TOTAL_CHARS,
    DEFAULT_CONTEXT_MAX_TURN_CHARS,
    DEFAULT_CONTEXT_MAX_TURNS,
    ConversationContextProjector,
)
from cognition.interaction_service import CognitiveInteractionService
from cognition.intent_interpreter import (
    IntentInterpretationError,
    IntentInterpreter,
    InvalidIntentInputError,
    RuleBasedIntentInterpreter,
)
from cognition.persistence import (
    CONVERSATION_SESSION_SCHEMA_VERSION,
    MAX_PERSISTED_TURN_SUMMARY_LENGTH,
    ConversationPersistenceCorruptionError,
    ConversationPersistenceError,
    ConversationPersistenceLoadError,
    ConversationPersistenceLoadResult,
    ConversationPersistenceWriteError,
    ConversationSessionRepository,
    LocalConversationSessionRepository,
    PersistedConversationSessionRecord,
    PersistedConversationTurnSummary,
    PersistedTurnContentClassification,
)
from cognition.sessions import (
    ConversationSessionClosedError,
    ConversationSessionNotFoundError,
    ConversationSessionService,
)
from cognition.response_composer import (
    CompatibilityResponseComposer,
    ResponseComposer,
)

__all__ = [
    "AssistantResponse",
    "AssistantResponseType",
    "CognitiveInteractionResult",
    "CognitiveInteractionService",
    "CompatibilityResponseComposer",
    "CONVERSATION_SESSION_SCHEMA_VERSION",
    "ConversationContextContentClassification",
    "ConversationContextProjector",
    "ConversationContextSnapshot",
    "ConversationContextTurn",
    "MAX_PERSISTED_TURN_SUMMARY_LENGTH",
    "DEFAULT_CONTEXT_MAX_TOTAL_CHARS",
    "DEFAULT_CONTEXT_MAX_TURN_CHARS",
    "DEFAULT_CONTEXT_MAX_TURNS",
    "ConversationPersistenceCorruptionError",
    "ConversationPersistenceError",
    "ConversationPersistenceLoadError",
    "ConversationPersistenceLoadResult",
    "ConversationPersistenceWriteError",
    "ConversationRole",
    "ConversationSessionClosedError",
    "ConversationSessionNotFoundError",
    "ConversationSessionRepository",
    "ConversationSessionService",
    "ConversationSessionSnapshot",
    "ConversationSessionStatus",
    "ConversationTurn",
    "ConversationTurnInput",
    "InvalidConversationTurnError",
    "IntentCategory",
    "IntentConfidence",
    "IntentEvidence",
    "IntentInterpretationError",
    "IntentInterpretationInput",
    "IntentInterpreter",
    "InterpretedIntent",
    "InvalidIntentInputError",
    "LocalConversationSessionRepository",
    "PersistedConversationSessionRecord",
    "PersistedConversationTurnSummary",
    "PersistedTurnContentClassification",
    "ResponseComposer",
    "ResponseCompositionInput",
    "ResponseCompositionResult",
    "RuleBasedIntentInterpreter",
]
